title: "Scaling Science"
author: "Development Seed and IEEE Geoscience and Remote Sensing Society"
email: "lilly@developmentseed.org"
release: "1"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
#logo: 'grss.png'

# Short description about the book
description: >-
  A course on science applied in industry, in collaboration with IEEE GRSS.

execute:
#  execute_notebooks           : auto
  execute_notebooks           : off
  timeout: -1

# HTML-specific settings
html:
#  favicon              : "grss.png"
  home_page_in_navbar  : false
  use_edit_page_button : true
  use_repository_button: true
  use_issues_button    : true
  extra_footer: |
     <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
     <a property="dct:title" rel="cc:attributionURL" 
      href="https://github.com/developmentseed/scaling_science">Scaling Science</a> is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Attribution 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1">
      <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" 
      src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a>
     </p> 

# Interact link settings
notebook_interface            : "notebook"

repository:
  url           : "https://github.com/developmentseed/scaling_science"
  branch        : main
  path_to_book  : book

# Launch button settings
#launch_buttons:
#  binder             : false
#  binderhub          : false
#  binderhub_url      : off
#  jupyterhub         : false
#  thebe              : false
#  colab              : false

# Launch button settings
launch_buttons:
#  notebook_interface: classic #jupyterlab
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com


# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
   
latex:
  latex_engine                : "pdflatex"
  use_jupyterbook_latex       : true # use jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: jb_book.tex
    
sphinx:
  config:
    html_show_copyright: false
    latex_toplevel_sectioning: 'section'
#    latex_show_urls: 'footnote'
    latex_elements.papersize: a4paper
    latex_elements.pointsize: 12pt

#google_analytics:
#  mytrackingcode: UA-205698170-1
